version: '3.8'

services:
  tiget-backend:
    image: tiget-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ["dotnet", "Presentation.dll", "--urls", "http://0.0.0.0:3000"]

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: Aa@12345
      ACCEPT_EULA: Y
      MSSQL_PID: Express
      MSSQL_DB_NAME: TiGet_1